services:
  postgres:
    image: postgres:15
    container_name: konektinda_db_prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: konektinda_app_prod
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT:-5433}/${DB_NAME}
      PORT: ${APP_PORT}
      NODE_ENV: production
      # Firebase Admin SDK
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      # Firebase Auth
      FIREBASE_AUTH_API_KEY: ${FIREBASE_AUTH_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_AUTH_PROJECT_ID: ${FIREBASE_AUTH_PROJECT_ID}
    ports:
      - '${APP_PORT}:4000'
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    command: npm run start:prod

volumes:
  postgres_data_prod:
    driver: local
